name: AWS connection test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6  

      - name: inspect OIDC claims
        run: |
          RESPONSE=$(curl -sS \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")   
          
          TOKEN=$(echo "$RESPONSE" | jp -r '.value')

          python - "$TOKEN" << 'py'
          import base64
          import json
          import sys

          token = sys.argv[1]
          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(base64.urlsafe_b64decode(payload))

          print(json.dumps({
              "iss": claims.get("iss"),
              "aud": claims.get("aud"),
              "sub": claims.get("sub"),
              "ref": claims.get("ref"),
              "repository": claims.get("repository"),
              "repository_id": claims.get("repository_id"),
              "repository_owner_id": claims.get("repository_owner_id")
              }, indent=2))
              py
              
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6 
        with:
          role-to-assume: arn:aws:iam::357817883234:role/github-actions-terraform-ec2
          aws-region: ap-south-1

      - name: test AWS connection
        run: aws sts get-caller-identity    